export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const ADD_USER = 'ADD_USER'
export const EDIT_USER = 'EDIT_USER'
export const REMOVE_USER = 'REMOVE_USER'

export const FETCH_SITE_START = 'FETCH_SITE_START'
export const FETCH_SITE_FAIL = 'FETCH_SITE_FAIL'
export const FETCH_SITE_SUCCESS = 'FETCH_SITE_SUCCESS'
export const ADD_SITE = 'ADD_SITE'
export const EDIT_SITE = 'EDIT_SITE'
export const REMOVE_SITE = 'REMOVE_SITE'
export const SAVE_SITE_FAIL = 'SAVE_SITE_FAIL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGOUT = 'LOGOUT'